version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0' -p 3000"
    volumes:
      - .:/blogApp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/blog_app_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    tty: true
    stdin_open: true

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: hashish
      POSTGRES_PASSWORD: hashish2024
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/blog_app_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development

volumes:
  postgres_data:

